#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。
name: 白日焰火
# 描述/签名
description: 互联网情感废墟bot

#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM4AAAD1CAMAAAAvfDqYAAAAkFBMVEX///8jHyAAAAAgHB0bFhcIAAAYEhQaFRYdGRofGhsTDQ/l5eUWERIKAAASCw34+Pjt7e0MAAXa2tr09PSGhIW/vr4xLi83NDWNjIzo6OheXF1wb2+XlpajoqIpJSbLyspSUFDT09O4t7dEQUJqaGl9fHydnJxBPj+sq6tLSUpgXl5vbW4tKSrOzc5XVVXExMT5cTBjAAAMC0lEQVR4nO1de3+qOBOWQQEVUayt97vWy2nt9/92LyBaUAiZmSDp+9vnnz3u2SV5SJjMPbXaf/i/Rn8FMKh6EnT02qmfP2Abhr/oVjQbLiYA3vH35xiMEO62uhlxsPIMw4TL/fepHtEx4L3CSZHxfV0MbxX/Xl5/G4Zzin6339/fKpscHns3XozR9ffWiekYENDobSHAptopYvBh3mbfD3/2b4sT/IufWq9hR3/6O3zu07ejz2fQutPxPmsL53eh/gR6idUIlwfM+293MPBuzEZVz1MS7V86rX1CEAQwh979j3bV85RE4lsxILXXAhKJv2oXP0oHpOgsa2aCQhJ/5RBK0vFGiS8pDf+z6onKIUmneXhv5NBp/RGVtJ1cD+vs5NBx97XP6Wxc9WwLkd5eeWwM82Q3XA+033K5X8sjn0hGgO7nT1eSTgzdBTaSjrWresIFwNHRfnmQdHTX3pB0mouqJyxGB0fHgF7VMxYiT0vLpfNT9YyF+EDS8edVz1iIQ64mkA3NtbcTko47rXrGQqzqODq23gfpxEbSOVc9YyF2SDqaqzlTC0cnsHx0xs0LKgtvVvWMhcDSaY36OvsQU64oKT4AH/oepSOvmMEjmjDUNZg1I9AJlmhVxlx6NhyL/yshPn0KHQO+lRBIY9AxgfmIOY1OKZooxPZHn27yHvM8hWKUoYmGU4F+bRNGyJbEZ2xodKx/Cnn095EDr2lGdMKYjNmh0kFa1zFUaqJraEGgpx/DmcD4OiGqi+W9ejq+GQVjWqEhCbHFQhU1PzQ6CjfbPjwqoDcPd71pxmkN10gtHksanZYyTbQdb67oH/Z0cIukn0jbbU2jo04TPUcq/eJKwx3dPUs2yWfUp9HpcI/vh/G/rovSXDXvQ5A2AJGOf1Skte3S9lbCr0QS1m0aHcOHr5ECD6JoeCC8sTGRTvD2VISvROYWhY5svCp7QG52y5todIo6KnxgEUyfSUdkbZkfhAci41UP4HqsRYPTTmoWHaadIFTnac9m0fF4wsBoCp5N03NYdBqs01SoLxK/S963QzWzIpxE/nGiVugiAzxpOpyTVKyQEN/UgkGnSZGld0xFHkuzQXvokEHH53w64gPcJTojtiLpUoD6iqGI7sTuZKCZINjwWwouPbe/0NACUpzvggy/pWGdqHSGhbuCpBGekfGqxzGJn8+8+IAw64Tn7pDxqscxHRIbKUWeohdgw29PY5LCPcIT9P5oQkItNl71NCZFqZbYakQ63NWhqG2SFj1ls3HOnRAUPX4hdzgQzFGWNRqCsDo7uRBZ/VL8qEdQgokp4De43IdDOneITtDkoFjn67dscjBhr3kc8yAa1ECOOAbJIRt4S3dOC1YlUJ/gRuw6kjqi6aHZ1IYc/fMK5A4fyupUhEOH55W6ArfFV7JZGZTMLKqDOoUG4uCZSMtRio+IGD5IwxlKj3dG5AXDAU1HyerIK6E7lOBpoF05Kr4d+bAsZm2i52Lp1OrcYycaVs6FtMLml+ADIlx1+jqsjF7QPWAzzcwWlg01SeKBjsRAPQP94gjVGyo+HhnFtw/485pi5s7YWo6MWrCR1dOSjyX5VD64ao7zVTjGgLAHOrRseraFUGgBd1eEISimWwSmY6owr7rvUnwr5EgLPRIfDyyOicwJn00AR6ziLEfnofmxGmyexYUwLlEMoTztXqgvS/CW3kYAnt00zXoL4PLoF2MqbqJAzA+Qd3K+uTODpFpeh8M6/ffYmpfHgdfZw9Zqe9pGi5CXktX+ejxaHNilthxTNcgr/v+uc5xEOXv4BzLcgm766OPRyRl4ylgaI+9wznvzMEmoq9ganjQyV2fTwGqcjxPMUqfzI/eu/7vlibnUt4Gffe7jFW9pAtsta8lFxrP5m77Fk23PCvUIeMLFMKxMg90WviO4Jw9z6Dy53Dc+109seJkVKP8Knutv4/9rwnibD3L6e8jdZ3nFnMXapbu4SmyW3z15fvdXWYIU/cSstTk2i19TvRXN5YgtJE+idX+X7R37o4mQEWMZyy16sxG2VyFm7seIZcF4Sldp0njOLlrKWrOO35OPUWQjcn20lZHJKHBAvG7HfmPacMHH09+pI/OcNol62/UPpnPXWp5UknlSP3s4Wdm6MH3VagRA4nlp2Y+N2lgHBdJVHZpplWCEVsG0YvPgTImN/6btupZe85QDpLWmQKrZDYDtbr/fHQCYivrL8ZSWt4LJ8e4FXw+Ac+S/GmaxT3WmWvKUB9ORiEb0DrTS3ddDMpF5qiTMVj7yvUJp7P8GH+nkOMkspYohX/2qIMGjfMiHQ1lVYS+CjUjwkU0jqxCobEl2oK1sACoPk1he/So4ODbJxub6wYEPbF4usZj/FXC2hJxpJTkrpYAUC6U1xXkFSHTUJHyVASB1U15oap46tCI6dIOsF4HYXF1T2UarC6txw6BlwLR9YtVejV0aph7m4jyn968j9mAqDzSRdgO7vkUx7BWHDTvFQzGa3HbdvKC7WjTBIPZeukNN6rQSNE+s9gBX6CPblPSp4sVBVYLdlzECP+6vBjah3igDAx2sBBNgqOZKEh2sBHOx5sq0O6TqncuFms/misqFgeKrYsSJVKWjNVDbkXdebTxONuohjUp3m4cvaisAu9CaDKcF6nvbV6a4OYdBGa2Sq1qeki5frGh5oKw2/bOXx7Id14Py7lDwX3z2OKv9TLWATkBJTSICZd+6+LLQb9Thgd2jsghKysdl2MwBWh61IbM89iUJazft1odgYw9GpbOp1TqlSANvP7z59UNV12I12MOA739fNPzHCEsj0MjOV/sdphbA4XX33v3jhkf87/lvXqsVNvy/XhK5qYPfeP0NsqyukwGaX8HUTwCNTgNg9/3zfj9ZlvPj6y+CYZf0eqHW8rY8HjdlaJZozNglygocmQpxYX4+lOY8ZYKbQ91SefsGH9Itn/Kg2SWKvGIXxu0lJYGrW7c0u3aQm7enmXTjiusmrTVoeWDy8XW7wJe537S7X5nS+uUXzrbq+T/im1W/yr6uQjnGBkPfobYqLxMTxgek43Xec8aG4+XWlIP2BzknRM9bYumVWOW7nihon4giu76qeurZeF/QCCmPEarCsUnoDqft8gTYDAlF4Xp+PVesp4CVCnrft97dYKVCSaFCZVi6qG+olCtiVeLNwKwPortuRcClV+mo6dzR/5zuBqjreTSW1e0t+K7VwgkDX0vNrRaapyTlrbTMAR5SVYwewrADDQ2fdP6r94kpQKeXe5SHVFII4OKOGq7PLQpsATScUFXGBLaghBvKWbjlHMD0fbnZdsLgM6ZShlwsVRLivRVf6zZpnLq4DMUGtcFvOYjpxAZZH+zGAFe60BrqpI3Gqo0VbZqwT4jZemBjFuimda1s06+rKAhTAyZPH43tAQwPBQaria1vLxO3EBZ8p4NZZgcAzrOfYCstTyDef3BRmy7NwSru6uwvUmwOm+VvJ5v1RUzIen3eRx66i7SvIL4158Ed0J8IczBNOCu42VsJusPkTN3TtSH7k4E2Eatzlj4qz/7XYx02ij9GfJ4EVtGdZz58avIJrYe3tuiRxP4M+Tx1vS40V01fGyXu1hzk2ig+rPt5DnxIxCF9Rw+j+54vGnXmChcio45IorrJYV1RrA63fNHropy9esb1JzI3D9Q18fHc+vJGr3c8XGT5bWXuIVFZHcbAbbsJS70lnHFN7G13JeF4U3cE4knGVtXFH3/LCBFtFwlpwLtNXiHiALDoUl6JjHl9QtvrBbi2JbSYi6+JId9AUwJ+9pedcLNIuLI95F2RlULimpiOrg7fDMhEGvTRroshc8mSLsJaAjLlQBrHS55wkYg46B48TUCmc6LW0bkHfBSmW3ma6NVSKMzHtnd/Z6/VihVr3fKtC1C4PJrYpLIoagvL7Y/1YhTaPZpVkxShqL0Y5fLqClGouRFusa8SBRdkmJp4DKQhkgZ1T79k+AIIas/q54FOETk5rHOTXyzN4tlyaG8hJ4r1x07RG7q1VaYtp41vCovuU6F8CH18U1j0HySCFwo8nWLZSHyn+Hjz4IMC7UqwEOhbYLm3u4wCo7q3/HtSOoXjbt+PE+H+mG6TjyO4GmaE0TGegm75YP9BFf4H4fvFndqMTysAAAAASUVORK5CYII=

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM4AAAD1CAMAAAAvfDqYAAAAkFBMVEX///8jHyAAAAAgHB0bFhcIAAAYEhQaFRYdGRofGhsTDQ/l5eUWERIKAAASCw34+Pjt7e0MAAXa2tr09PSGhIW/vr4xLi83NDWNjIzo6OheXF1wb2+XlpajoqIpJSbLyspSUFDT09O4t7dEQUJqaGl9fHydnJxBPj+sq6tLSUpgXl5vbW4tKSrOzc5XVVXExMT5cTBjAAAMC0lEQVR4nO1de3+qOBOWQQEVUayt97vWy2nt9/92LyBaUAiZmSDp+9vnnz3u2SV5SJjMPbXaf/i/Rn8FMKh6EnT02qmfP2Abhr/oVjQbLiYA3vH35xiMEO62uhlxsPIMw4TL/fepHtEx4L3CSZHxfV0MbxX/Xl5/G4Zzin6339/fKpscHns3XozR9ffWiekYENDobSHAptopYvBh3mbfD3/2b4sT/IufWq9hR3/6O3zu07ejz2fQutPxPmsL53eh/gR6idUIlwfM+293MPBuzEZVz1MS7V86rX1CEAQwh979j3bV85RE4lsxILXXAhKJv2oXP0oHpOgsa2aCQhJ/5RBK0vFGiS8pDf+z6onKIUmneXhv5NBp/RGVtJ1cD+vs5NBx97XP6Wxc9WwLkd5eeWwM82Q3XA+033K5X8sjn0hGgO7nT1eSTgzdBTaSjrWresIFwNHRfnmQdHTX3pB0mouqJyxGB0fHgF7VMxYiT0vLpfNT9YyF+EDS8edVz1iIQ64mkA3NtbcTko47rXrGQqzqODq23gfpxEbSOVc9YyF2SDqaqzlTC0cnsHx0xs0LKgtvVvWMhcDSaY36OvsQU64oKT4AH/oepSOvmMEjmjDUNZg1I9AJlmhVxlx6NhyL/yshPn0KHQO+lRBIY9AxgfmIOY1OKZooxPZHn27yHvM8hWKUoYmGU4F+bRNGyJbEZ2xodKx/Cnn095EDr2lGdMKYjNmh0kFa1zFUaqJraEGgpx/DmcD4OiGqi+W9ejq+GQVjWqEhCbHFQhU1PzQ6CjfbPjwqoDcPd71pxmkN10gtHksanZYyTbQdb67oH/Z0cIukn0jbbU2jo04TPUcq/eJKwx3dPUs2yWfUp9HpcI/vh/G/rovSXDXvQ5A2AJGOf1Skte3S9lbCr0QS1m0aHcOHr5ECD6JoeCC8sTGRTvD2VISvROYWhY5svCp7QG52y5todIo6KnxgEUyfSUdkbZkfhAci41UP4HqsRYPTTmoWHaadIFTnac9m0fF4wsBoCp5N03NYdBqs01SoLxK/S963QzWzIpxE/nGiVugiAzxpOpyTVKyQEN/UgkGnSZGld0xFHkuzQXvokEHH53w64gPcJTojtiLpUoD6iqGI7sTuZKCZINjwWwouPbe/0NACUpzvggy/pWGdqHSGhbuCpBGekfGqxzGJn8+8+IAw64Tn7pDxqscxHRIbKUWeohdgw29PY5LCPcIT9P5oQkItNl71NCZFqZbYakQ63NWhqG2SFj1ls3HOnRAUPX4hdzgQzFGWNRqCsDo7uRBZ/VL8qEdQgokp4De43IdDOneITtDkoFjn67dscjBhr3kc8yAa1ECOOAbJIRt4S3dOC1YlUJ/gRuw6kjqi6aHZ1IYc/fMK5A4fyupUhEOH55W6ArfFV7JZGZTMLKqDOoUG4uCZSMtRio+IGD5IwxlKj3dG5AXDAU1HyerIK6E7lOBpoF05Kr4d+bAsZm2i52Lp1OrcYycaVs6FtMLml+ADIlx1+jqsjF7QPWAzzcwWlg01SeKBjsRAPQP94gjVGyo+HhnFtw/485pi5s7YWo6MWrCR1dOSjyX5VD64ao7zVTjGgLAHOrRseraFUGgBd1eEISimWwSmY6owr7rvUnwr5EgLPRIfDyyOicwJn00AR6ziLEfnofmxGmyexYUwLlEMoTztXqgvS/CW3kYAnt00zXoL4PLoF2MqbqJAzA+Qd3K+uTODpFpeh8M6/ffYmpfHgdfZw9Zqe9pGi5CXktX+ejxaHNilthxTNcgr/v+uc5xEOXv4BzLcgm766OPRyRl4ylgaI+9wznvzMEmoq9ganjQyV2fTwGqcjxPMUqfzI/eu/7vlibnUt4Gffe7jFW9pAtsta8lFxrP5m77Fk23PCvUIeMLFMKxMg90WviO4Jw9z6Dy53Dc+109seJkVKP8Knutv4/9rwnibD3L6e8jdZ3nFnMXapbu4SmyW3z15fvdXWYIU/cSstTk2i19TvRXN5YgtJE+idX+X7R37o4mQEWMZyy16sxG2VyFm7seIZcF4Sldp0njOLlrKWrOO35OPUWQjcn20lZHJKHBAvG7HfmPacMHH09+pI/OcNol62/UPpnPXWp5UknlSP3s4Wdm6MH3VagRA4nlp2Y+N2lgHBdJVHZpplWCEVsG0YvPgTImN/6btupZe85QDpLWmQKrZDYDtbr/fHQCYivrL8ZSWt4LJ8e4FXw+Ac+S/GmaxT3WmWvKUB9ORiEb0DrTS3ddDMpF5qiTMVj7yvUJp7P8GH+nkOMkspYohX/2qIMGjfMiHQ1lVYS+CjUjwkU0jqxCobEl2oK1sACoPk1he/So4ODbJxub6wYEPbF4usZj/FXC2hJxpJTkrpYAUC6U1xXkFSHTUJHyVASB1U15oap46tCI6dIOsF4HYXF1T2UarC6txw6BlwLR9YtVejV0aph7m4jyn968j9mAqDzSRdgO7vkUx7BWHDTvFQzGa3HbdvKC7WjTBIPZeukNN6rQSNE+s9gBX6CPblPSp4sVBVYLdlzECP+6vBjah3igDAx2sBBNgqOZKEh2sBHOx5sq0O6TqncuFms/misqFgeKrYsSJVKWjNVDbkXdebTxONuohjUp3m4cvaisAu9CaDKcF6nvbV6a4OYdBGa2Sq1qeki5frGh5oKw2/bOXx7Id14Py7lDwX3z2OKv9TLWATkBJTSICZd+6+LLQb9Thgd2jsghKysdl2MwBWh61IbM89iUJazft1odgYw9GpbOp1TqlSANvP7z59UNV12I12MOA739fNPzHCEsj0MjOV/sdphbA4XX33v3jhkf87/lvXqsVNvy/XhK5qYPfeP0NsqyukwGaX8HUTwCNTgNg9/3zfj9ZlvPj6y+CYZf0eqHW8rY8HjdlaJZozNglygocmQpxYX4+lOY8ZYKbQ91SefsGH9Itn/Kg2SWKvGIXxu0lJYGrW7c0u3aQm7enmXTjiusmrTVoeWDy8XW7wJe537S7X5nS+uUXzrbq+T/im1W/yr6uQjnGBkPfobYqLxMTxgek43Xec8aG4+XWlIP2BzknRM9bYumVWOW7nihon4giu76qeurZeF/QCCmPEarCsUnoDqft8gTYDAlF4Xp+PVesp4CVCnrft97dYKVCSaFCZVi6qG+olCtiVeLNwKwPortuRcClV+mo6dzR/5zuBqjreTSW1e0t+K7VwgkDX0vNrRaapyTlrbTMAR5SVYwewrADDQ2fdP6r94kpQKeXe5SHVFII4OKOGq7PLQpsATScUFXGBLaghBvKWbjlHMD0fbnZdsLgM6ZShlwsVRLivRVf6zZpnLq4DMUGtcFvOYjpxAZZH+zGAFe60BrqpI3Gqo0VbZqwT4jZemBjFuimda1s06+rKAhTAyZPH43tAQwPBQaria1vLxO3EBZ8p4NZZgcAzrOfYCstTyDef3BRmy7NwSru6uwvUmwOm+VvJ5v1RUzIen3eRx66i7SvIL4158Ed0J8IczBNOCu42VsJusPkTN3TtSH7k4E2Eatzlj4qz/7XYx02ij9GfJ4EVtGdZz58avIJrYe3tuiRxP4M+Tx1vS40V01fGyXu1hzk2ig+rPt5DnxIxCF9Rw+j+54vGnXmChcio45IorrJYV1RrA63fNHropy9esb1JzI3D9Q18fHc+vJGr3c8XGT5bWXuIVFZHcbAbbsJS70lnHFN7G13JeF4U3cE4knGVtXFH3/LCBFtFwlpwLtNXiHiALDoUl6JjHl9QtvrBbi2JbSYi6+JId9AUwJ+9pedcLNIuLI95F2RlULimpiOrg7fDMhEGvTRroshc8mSLsJaAjLlQBrHS55wkYg46B48TUCmc6LW0bkHfBSmW3ma6NVSKMzHtnd/Z6/VihVr3fKtC1C4PJrYpLIoagvL7Y/1YhTaPZpVkxShqL0Y5fLqClGouRFusa8SBRdkmJp4DKQhkgZ1T79k+AIIas/q54FOETk5rHOTXyzN4tlyaG8hJ4r1x07RG7q1VaYtp41vCovuU6F8CH18U1j0HySCFwo8nWLZSHyn+Hjz4IMC7UqwEOhbYLm3u4wCo7q3/HtSOoXjbt+PE+H+mG6TjyO4GmaE0TGegm75YP9BFf4H4fvFndqMTysAAAAASUVORK5CYII=

# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags



# 每页的文章数
paginate: 15

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: #claradoesntcare #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: conundrum1804@gmail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: #FromEndWorld/loffer #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2019 这不是一部《会饮集》

# 评论，注意，请不要同时添加多种不同的评论区

# 输入Disqus shortname，即可添加评论区

# 输入Gitalk相关设定，即可添加评论区
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# 输入Google Analytics web tracking code
google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: 

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

